inventory/__init__.py
from flask import Flask
from flask_restx import Resource,Api
from inventory.config import Config
from inventory.db import init_db,mongo
from inventory.routes.views import main
from inventory.routes.api_routes import api
from inventory.auth.auth import auth

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    init_db(app)



    app.register_blueprint(main) 
    app.register_blueprint(auth)
    api.init_app(app)
    
    return app


    

inventory/routes/api_routes.py
from flask import g
from flask_restx import Api,Resource
from inventory.auth.auth import login_required
from inventory.db import mongo


api=Api(doc='/api/docs')

"""Return the employee list
The returned data is in json form, ie a dictionary
"""

@api.route("/employees")
class Employees(Resource):
    def get(self):
        employees=mongo.db.employees.find()
        employee_list=[]
        for employee in employees:
            employee_list.append({
                'id':str(employee['_id']),
                'name':employee['name'],
                'salary':employee['salary'],
                'position':employee['position']
            })
        return {'employees':employee_list}

inventory/routes/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session,g
from bson.objectid import ObjectId
from inventory.db import mongo

main = Blueprint('main', __name__)

@main.route('/')
def index():
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    print(g.user,"1")
    employees = mongo.db.employees.find()
    return render_template('index.html', employees=employees)

@main.route('/employee/<id>')
def employee(id):
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    employee = mongo.db.employees.find_one_or_404({'_id': ObjectId(id)})
    return render_template('employee.html', employee=employee)

@main.route('/add', methods=['GET', 'POST'])
def add_employee():
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    if request.method == 'POST':
        name = request.form['name']
        position = request.form.get('position')
        salary = request.form.get('salary')
        mongo.db.employees.insert_one({'name': name, 'position': position, 'salary': salary})
        return redirect(url_for('main.index'))
    return render_template('add_employee.html')

@main.route('/edit/<id>', methods=['GET', 'POST'])
def edit_employee(id):
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    employee = mongo.db.employees.find_one_or_404({'_id': ObjectId(id)})
    if request.method == 'POST':
        name = request.form.get('name')
        position = request.form.get('position')
        salary = request.form.get('salary')
        mongo.db.employees.update_one({'_id': ObjectId(id)}, {'$set': {'name': name, 'position': position, 'salary': salary}})
        return redirect(url_for('main.employee', id=id))
    return render_template('edit_employee.html', employee=employee)

@main.route('/delete/<id>', methods=['POST'])
def delete_employee(id):
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    mongo.db.employees.delete_one({'_id': ObjectId(id)})
    return redirect(url_for('main.index'))

inventory/templates/add_employee.html
{% extends "base.html" %}

{% block title %}Add Employee{% endblock %}

{% block content %}
<h1>Add Employee</h1>
<form method="POST">
    <label for="name">Name:</label>
    <input type="text" id="name" name="name"><br>
    <label for="position">Position:</label>
    <input type="text" id="position" name="position"><br>
    <label for="salary">Salary:</label>
    <input type="text" id="salary" name="salary"><br>
    <button type="submit">Add Employee</button>
</form>
{% endblock %}

inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Employee Management{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <nav>
        <ul style="display:flex; justify-content:space-between">
            <div class='left navbar' style="display:flex; gap:10px;">
              <div style="display:flex; margin-right:4vw;"><span style="color:orange;">Pal</span><span style="color:blue">Tech</span></div>
            <li><a href="{{ url_for('main.index') }}">Home</a></li>
            <li><a href="{{ url_for('main.add_employee') }}">Add Employee</a></li>
            </div>
            <div class='right navbar' style="display:flex;">
            <li><a href="{{url_for('auth.logout')}}">Log Out </a></li>
            </div>
        </ul>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

inventory/templates/edit_employee.html
{% extends "base.html" %}

{% block title %}Edit Employee{% endblock %}

{% block content %}
<h1>Edit Employee</h1>
<form method="POST">
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" value="{{ employee.name }}"><br>
    <label for="position">Position:</label>
    <input type="text" id="position" name="position" value="{{ employee.position }}"><br>
    <label for="salary">Salary:</label>
    <input type="text" id="salary" name="salary" value="{{ employee.salary }}"><br>
    <button type="submit">Update Employee</button>
</form>
{% endblock %}

inventory/templates/employee.html
{% extends "base.html" %}

{% block title %}Employee Details{% endblock %}

{% block content %}
<img class='img-user'src="../static/img/user.png" alt="user.png">
<h1>{{employee.name}} s Details</h1>
<p><strong>Name:</strong> {{ employee.name }}</p>
<p><strong>Position:</strong> {{ employee.position }}</p>
<p><strong>Salary:</strong> {{ employee.salary }}</p>

<div class='link-group' style="display:flex; gap: 5vw;">
<a class='edit-link' href="{{ url_for('main.edit_employee', id=employee._id) }}">Edit</a>
<a class='edit-link' href="{{ url_for('main.index') }}">Back to Employee List</a>
</div>
{% endblock %}

inventory/templates/index.html
{% extends "base.html" %}

{% block title %}Employee List{% endblock %}

{% block content %}
<h1>Employee List</h1>
<ul class="employee-list">
    {% for employee in employees %}
        <li class="employee-item">
            <div class="employee-details">
                <a href="{{ url_for('main.employee', id=employee._id) }}" class="employee-name">{{ employee.name }}</a>
                <span class="employee-position">{{ employee.position }}</span>
                <span class="employee-salary">{{ employee.salary }}</span>
            </div>
<div class="employee-actions" style="display:flex; align-items:center">
                <a style="margin-top:11px;" href="{{ url_for('main.edit_employee', id=employee._id) }}" class="edit-link">Edit</a>
                <form style="all:unset;" action="{{ url_for('main.delete_employee', id=employee._id) }}" method="POST" style="display:inline;">
                    <button type="submit" style="margin-bottom:3px;" class="delete-button">Delete</button>
                </form>
            </div>
        </li>
    {% endfor %}
</ul>
{% endblock %}

inventory/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
{% if error %}
<dialog open>
  <p>{{error}}</p>
</dialog>
{% endif %}
<img class='header-img' src={{url_for('static',filename='img/conversation_business_03.jpg')}} alt="company.png">
<h1>Login</h1>
<form method="POST">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br>
    <button type="submit">Login</button>
</form>
<p>Don't have an account? <a href="{{ url_for('auth.register') }}">Register here</a></p>
{% endblock %}

inventory/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<h1>Register</h1>
<form method="POST">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br>
    <button type="submit">Register</button>
</form>
<p>Already have an account? <a href="{{ url_for('auth.login') }}">Login here</a></p>
{% endblock %}